### ISSUE TITLE
Can't find synonyms.js error when tap not installed

### ISSUE THREAD

**Issue by jtlapp** [jtlapp/subtap#2]
When test files exist but tap is not installed, the following unhelpful error occurs. Should produce a more informative error.

```
module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/joe/lib/synonyms.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/joe/repos/subtap/bin/_runfile.js:14:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
*** no subtests found ***
```

(Calling this a bug too, because it presents a confusing situation.)

**Comment by jtlapp** [comment]
Resolved in latest commit. Have one feature to add before publishing.
